# for jekyll
permalink: /:title
url: https://blog.dm4.tw

# for jekyll-feed
author: dm4
feed:
  posts_limit: 99999  # unlimited
defaults:
  - scope:
      path: ""
    values:
      lang: zh-TW     # for xml:lang

# for jekyll-seo-tag
locale: zh_TW         # for og:locale

# for the-plain theme
author_name: dm4
logo_url: https://s.gravatar.com/avatar/1b0b7bab4c837d80e1b110bd7127a0d8?s=750

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
remote_theme: heiswayi/the-plain

# show posts with future date
future: true
